def currency_symbols_set() -> set[str]:
    currency_symbols = {
        "د.إ",
        "؋",
        "L",
        "֏",
        "ƒ",
        "Kz",
        "ARS$",
        "₼",
        "KM",
        "Bds$",
        "৳",
        ".د.ب",
        "FBu",
        "BD$",
        "B$",
        "Bs.",
        "R$",
        "Nu",
        "P",
        "Br",
        "BZ$",
        "C$",
        "FC",
        "CHF",
        "CLP$",
        "¥",
        "COL$",
        "₡",
        "₱",
        "Esc",
        "Kč",
        "Fdj",
        "kr",
        "RD$",
        "دج",
        "E£",
        "Nfk",
        "€",
        "FJ$",
        "FK£",
        "£",
        "₾",
        "GH₵",
        "G$",
        "G",
        "Rp",
        "₪",
        "₹",
        "ع.د",
        "﷼",
        "J$",
        "دينار",
        "KSh",
        "som",
        "៛",
        "CF",
        "₩",
        "ك",
        "CI$",
        "₸",
        "₭",
        "ل.ل",
        "Rs",
        "LD$",
        "M",
        "LD",
        "DH",
        "Ar",
        "ден",
        "₮",
        "MOP$",
        "UM",
        "₨",
        "Rf",
        "K",
        "Mex$",
        "RM",
        "N$",
        "₦",
        "Rs",
        "NZ$",
        "ر.ع.",
        "B./",
        "S/.",
        "₲",
        "zł",
        "Q",
        "lei",
        "Din.",
        "₽",
        "R₣",
        "﷼",
        "SI$",
        "SR",
        "SDG",
        "S$",
        "Le",
        "Sh.So.",
        "SR$",
        "Db",
        "£S",
        "TJS",
        "m",
        "T$",
        "₺",
        "TT$",
        "NT$",
        "TSh",
        "₴",
        "USh",
        "$",
        "$U",
        "UZS",
        "Bs.",
        "₫",
        "FCFA",
        "CFA",
        "₣",
        "﷼",
        "R",
        "ZK",
        "Z$",
        "₿",
        "Ξ",
        "Ł",
        "ɱ",
    }

    return currency_symbols.copy()


def currency_codes() -> dict[str, str]:
    currency_codes_dict = {
        "AED": "د.إ",
        "AFN": "؋",
        "ALL": "L",
        "AMD": "֏",
        "ANG": "ƒ",
        "AOA": "Kz",
        "ARS": "ARS$",
        "AWG": "ƒ",
        "AZN": "₼",
        "BAM": "KM",
        "BBD": "Bds$",
        "BDT": "৳",
        "BHD": ".د.ب",
        "BIF": "FBu",
        "BMD": "BD$",
        "BND": "B$",
        "BOB": "Bs.",
        "BOP": "Bs.",
        "BOV": "Bs.",
        "BRL": "R$",
        "BSD": "B$",
        "BTN": "Nu",
        "BWP": "P",
        "BYN": "Br",
        "BZD": "BZ$",
        "CAD": "C$",
        "CDF": "FC",
        "CHF": "CHF",
        "CLP": "CLP$",
        "CNY": "¥",
        "COP": "COL$",
        "CRC": "₡",
        "CUP": "₱",
        "CVE": "Esc",
        "CZK": "Kč",
        "DJF": "Fdj",
        "DKK": "kr",
        "DOP": "RD$",
        "DZD": "دج",
        "EGP": "E£",
        "ERN": "Nfk",
        "ETB": "Br",
        "EUR": "€",
        "FJD": "FJ$",
        "FKP": "FK£",
        "GBP": "£",
        "GEL": "₾",
        "GHS": "GH₵",
        "GIP": "£",
        "GMD": "D",
        "GNF": "FG",
        "GTQ": "Q",
        "GYD": "G$",
        "HKD": "HK$",
        "HNL": "L",
        "HRK": "kn",
        "HTG": "G",
        "HUF": "ft",
        "IDR": "Rp",
        "ILS": "₪",
        "INR": "₹",
        "IQD": "ع.د",
        "IRR": "﷼",
        "ISK": "kr",
        "JMD": "J$",
        "JOD": "دينار",
        "JPY": "¥",
        "KES": "KSh",
        "KGS": "som",
        "KHR": "៛",
        "KMF": "CF",
        "KPW": "₩",
        "KRW": "₩",
        "KWD": "ك",
        "KYD": "CI$",
        "KZT": "₸",
        "LAK": "₭",
        "LBP": "ل.ل",
        "LKR": "Rs",
        "LRD": "LD$",
        "LSL": "M",
        "LYD": "LD",
        "MAD": "DH",
        "MDL": "L",
        "MGA": "Ar",
        "MKD": "ден",
        "MMK": "K",
        "MNT": "₮",
        "MOP": "MOP$",
        "MRU": "UM",
        "MUR": "₨",
        "MVR": "Rf",
        "MWK": "K",
        "MXN": "Mex$",
        "MYR": "RM",
        "NAD": "N$",
        "NGN": "₦",
        "NIO": "C$",
        "NOK": "kr",
        "NPR": "Rs",
        "NZD": "NZ$",
        "OMR": "ر.ع.",
        "PAB": "B./",
        "PEN": "S/.",
        "PGK": "K",
        "PHP": "₱",
        "PKR": "₨",
        "PLN": "zł",
        "PYG": "₲",
        "QAR": "ر.ق",
        "RON": "lei",
        "RSD": "Din.",
        "RUB": "₽",
        "RWF": "R₣",
        "SAR": "﷼",
        "SBD": "SI$",
        "SCR": "SR",
        "SDG": "SDG",
        "SEK": "kr",
        "SGD": "S$",
        "SHP": "£",
        "SLL": "Le",
        "SOS": "Sh.So.",
        "SRD": "SR$",
        "STN": "Db",
        "SYP": "£S",
        "SZL": "L",
        "THB": "฿",
        "TJS": "TJS",
        "TMT": "m",
        "TND": "د.ت",
        "TOP": "T$",
        "TRY": "₺",
        "TTD": "TT$",
        "TWD": "NT$",
        "TZS": "TSh",
        "UAH": "₴",
        "UGX": "USh",
        "USD": "$",
        "UYU": "$U",
        "UZS": "UZS",
        "VED": "Bs.",
        "VND": "₫",
        "XAF": "FCFA",
        "XCD": "$",
        "XOF": "CFA",
        "XPF": "₣",
        "YER": "﷼",
        "ZAR": "R",
        "ZMW": "ZK",
        "ZWD": "Z$",
        "BTC": "₿",
        "ETH": "Ξ",
        "LTC": "Ł",
        "XMR": "ɱ",
    }
    return currency_codes_dict.copy()
