services:
    redis:
        image: ENC[AES256_GCM,data:qADTGONgHJhGFoD3HMoIsHnm,iv:N0A99WWFUKf1EdblP9Jv+t/oQV8KYivEBV7IjdfyUOU=,tag:OYrE5cp0BQw1TzrXRTDlKA==,type:str]
        restart: ENC[AES256_GCM,data:cDezFjJZ/D+S3zaAPl8=,iv:H2Bpci+ccBy/ZD0MU4qLi5YEiY/DPYBI3OzukqumZLE=,tag:p+oBCtQ3W/qsF/XHWuf61A==,type:str]
        container_name: ENC[AES256_GCM,data:yJsJ+zg=,iv:1B+E4PVF19ePMpi0MYstmcOlT4hX86cgVyQ0Spqz8No=,tag:od4JsIlWjFWg5NP4UMZhYA==,type:str]
        environment:
            PORT: ENC[AES256_GCM,data:8Qa+gA==,iv:6AUcOmAVRm5ptnkMw6exCTYcQGVk3I8v2hXIRY1VyeA=,tag:4c3op2lPfNLiW9RR+5pQWg==,type:int]
        networks:
            - ENC[AES256_GCM,data:I7Kx,iv:+zzGV0UbyTmMDGgkz7ME2skjB94Av1Pem9nlh5wv7C8=,tag:6cSccOl7yUjq+1ZmUNpvTg==,type:str]
    db:
        image: ENC[AES256_GCM,data:Lw3V/X8=,iv:k8j4HKgzfGHJu2Wx/tsD68FGFP98qm9/PsFmyuMZDyE=,tag:lIa99ielFbNhvyvoG3YgMQ==,type:str]
        restart: ENC[AES256_GCM,data:4pu/1PlkaIfMFFicczg=,iv:NjzWDxNclWYM1SMEOoki+IbODYRiYRBAJ4N1SMqs75k=,tag:SicfKCUCy+ViXTFLjdqv9Q==,type:str]
        container_name: ENC[AES256_GCM,data:p0HTWq8=,iv:M40GvlRvx0Q0ypQlZdusyNodyQtQ9STPcIEAEeP1W6U=,tag:SRw7fAngkVuU+jjAiVaaoA==,type:str]
        environment:
            PORT: ENC[AES256_GCM,data:3kNRQRo=,iv:kUPy9hSJj1aaCTH8DTE3AfSwvZUqPpb+3OXv6tT7K+Y=,tag:zxMULVIgGPhE0S4Z+Y04CA==,type:int]
            MONGO_INITDB_ROOT_USERNAME: ENC[AES256_GCM,data:NLBJfpD7fvEs04RG,iv:5lENB59Dd+VFb7Bik9aYmDKf1382NZAawBFYis/Oh74=,tag:11WgekwCS0TkJgMQGhvgpg==,type:str]
            MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:wosJw+GlWGBMNfK1B2JDlYtA,iv:wFlMNnm+UkrbsxmrK0nzN0yNV7gZiyoSF1ht+w2+T5I=,tag:yy3xMPpC9DaGH+4xoCvHmg==,type:str]
        volumes:
            - ENC[AES256_GCM,data:iImeT14xn3LHWSSjPU7qRVgeteGRDQ0=,iv:W4s9x4u9fY8tqnpuFjo6q2mvev0UIqydfs/a08HAVWs=,tag:bG9BDvTkEITISD9OIGJUUA==,type:str]
            - ENC[AES256_GCM,data:9eI8S4YWu7phNGSCsPJkJBL/NZsnJfCMXZZiRbYCshKVOziJ/A==,iv:FOJTgy4PyIPMtWk0iM0GlPV3bWDOEmSJmLbXMsZJ1gU=,tag:qodMKNHtR25+u4yibAqflA==,type:str]
        command:
            - ENC[AES256_GCM,data:s9+Xe/os,iv:llKW2XxW4/x3renZP2iTr03SIEyZkjyDFMiTqTGrwfk=,tag:eLZT8qbJZExM3dM2jIHIjQ==,type:str]
            - ENC[AES256_GCM,data:FfH5KDjScCi7,iv:AQ/uVUgPFmaXZsAx9tHjK3k2pGcaq5Q2tyBOpYjGi6o=,tag:bBGYNHCFFXRk1R7XVH1poA==,type:str]
            - ENC[AES256_GCM,data:U4Kd,iv:S4DfOxf4VlWNGCdjnsVGTf4QqCAlxaAFWWfpZWc6Puo=,tag:074PbIXVP/A02O1WBu1QoA==,type:str]
            - ENC[AES256_GCM,data:u8bP1rQeYY9O4ejuwg==,iv:5wIhtIDrNML9O8vvDP9ULKOEcls6VpG+WbrXOk8EE0U=,tag:KcxMommYgI2BfQQW4hzCuQ==,type:str]
            - ENC[AES256_GCM,data:CUs65xdj,iv:QlXthFclzKfH2cnnytKLwi/rGlEFcV8DWG2cjzh2iA8=,tag:MvlM34DvCoqoaoDKAPEk7g==,type:str]
            - ENC[AES256_GCM,data:dji+Ru5DRl5c,iv:DtmVE+qSwdqqCwj2pK+FD2XjoU0UyBXQXON/ILL6xyg=,tag:nlZ65zZnB0eXyzbNxW57DA==,type:str]
            - ENC[AES256_GCM,data:kwtM9vEWoS5BNOTSFzHzXNeR,iv:mvl2uzF+XDRSbIWGfIt2/y7DkiS1eUT5jFGT74YHmj4=,tag:FysitLH8bjXoma8zLLevrg==,type:str]
        networks:
            - ENC[AES256_GCM,data:jFsD,iv:GcvwhDGRCIq0IOxlgnrhv6ePmD4FLclkMuW86n4YOXY=,tag:8diSz+6dLC2R64dXN6dZzA==,type:str]
    celery-worker:
        build:
            context: ENC[AES256_GCM,data:gHcNAnfzEwQaWQ==,iv:1zmRhLz9uuk6WK/hw7oE27Y+2P16kTgYvd33T4LtjA4=,tag:teJmL4pEUZZZ4sOY1QKiVQ==,type:str]
            dockerfile: ENC[AES256_GCM,data:Rgrp/lmIM8WUfr22rRnAKDNNLKWGkLvqbV5jeoU=,iv:gCOD3Q8+9plmvwY5Xf5phe69b4q+QG3/LiYNAub156w=,tag:dc4JI4/IQsTwdAOGbZ2Dkg==,type:str]
        container_name: ENC[AES256_GCM,data:GR4JLoVx,iv:3UbqaA6MyUnXgG6V5TLIYnCJKIOhuBd4zqJOEg9oX1o=,tag:MrKlnawdKgo0qA0WQz3tpg==,type:str]
        restart: ENC[AES256_GCM,data:/6xIDkpuQVZK0WWZ4b0=,iv:YJiugFNYImPaJSbkJw7XJ9grAwM0J8XQq7RWfZPSVsE=,tag:XZHCV0fjIowqc0QSwIsGpA==,type:str]
        environment:
            PORT: ENC[AES256_GCM,data:9BvtrQ==,iv:1qMwavB/cR5Tny3krc4VkwKXEvPe0hgzhA3IjkmbDr0=,tag:fmZ1ZUpP0gJz/ElwZAY8GA==,type:int]
            REDIS_PORT: ENC[AES256_GCM,data:wBCfJg==,iv:neC603Moy0Rv2y2e4zU8CPORbIBpvq+s9YR9KvAiNa0=,tag:P6vo1OOhetM9v0x9g4FndA==,type:int]
            REDIS_HOST: ENC[AES256_GCM,data:v7vx0ZI=,iv:avRBhkXKtCeHLAzRzaCn25529JVUkh1DxBnOao36b1U=,tag:pFxS6Z7J9i6InN9S6DNhkw==,type:str]
            FIREBASE_AUTH_PROJECT_ID: ENC[AES256_GCM,data:HL8lF4RF,iv:5eDsMfHQfc4c/FI1ux8XpbjKwtqdg9/pjeWlH8h695g=,tag:xyKk6CSoNLVWmhELL2ibmQ==,type:str]
            PROXY_URL: ENC[AES256_GCM,data:g9CFet2WnEWWw151od4=,iv:OlalvTusLy9Yhg7+wsA1R0sRuJ2k9Cq9N06au2cevME=,tag:eDRFiiWjJ28dfM+AT+QogQ==,type:str]
            ADMIN_DISCORD_WEBHOOK: ENC[AES256_GCM,data:hy0BmHZ65QO+HfG9jBbYebChAb4gjPAi3Lpark+1gD2yEgNG5op9Lsujgf5jl92hLqNbaVdZ/168QOPNnbjvlHbwpb3+7KzJzloB9FojrF0P+3+7fFhc42P3QHdmSEhkOKGob2BeSvLTbJZ8NxLuCMSQhWmLTcLNmw==,iv:Zj11AkkgOnnWXTOFJiZq0gzLItcHPWzHppZZRfiKXhg=,tag:nrJeEGPysgXaf69Az6xXag==,type:str]
            DB_USERNAME: ENC[AES256_GCM,data:XcKpH+DGLAIZED7m,iv:ZthZ4kZO7j5loo2p+DDGroYCKKjyi/eUn4aJlQFZUgk=,tag:O0aVjb8qaBzwt6htqBrzpg==,type:str]
            DB_PASSWORD: ENC[AES256_GCM,data:z1QLQCKs8lu5C4P/vDHDYaXb,iv:x+HMVvnFkJnS5Lna13X+gzZebXe90BaI7sW55BQWqB0=,tag:2pk4O/1sGIj6eY6mRWjXYQ==,type:str]
            DB_AUTH_SOURCE: ENC[AES256_GCM,data:ANA5H1A=,iv:czfpaHtHxL7b05CU1zAlpMh2eeE+vM5+FnogdInTrrI=,tag:ybrPhZjWDKgu52koWVoY+w==,type:str]
            DB_NAME: ENC[AES256_GCM,data:cqUVEgZr,iv:WDAa1xiCtk/4htTDGjV2kx/WJ+5upDPcBx7G0jxe3uI=,tag:BPxE/6kaJ1bd/rnXCdsRvw==,type:str]
            DB_HOST: ENC[AES256_GCM,data:lMg=,iv:C9+zyDviU2z6iFFua3N7045UTof2o7Qv1FVG4KIDrzU=,tag:3gIKWOH7lyVmm8GBgmQ8PQ==,type:str]
            DB_PORT: ENC[AES256_GCM,data:Ne6lElA=,iv:8UKur1A5tFJsI2LT1nQ1VNEooQelbKZitNgdxq2p/zI=,tag:CG0+spKklr5haO/ceXKBXw==,type:int]
            DB_REPLICASET: ENC[AES256_GCM,data:zI3I,iv:M3I1/7othZeW8IC1frYLrfEnhtLBFcA7UIsTXKb25+M=,tag:/sunCc/kzB6RN2Sh+Eq11g==,type:str]
            INTERVAL_HOUR: ENC[AES256_GCM,data:GUrc,iv:xt/+Sh65vUWkXn2xg7P06PEVuhYLhQVVep8j00BC2IU=,tag:1Vf3wYQPaNtWGAc5ZlKq2A==,type:str]
            INTERVAL_MIN: ENC[AES256_GCM,data:8Q==,iv:2tPt3UsjBDKAQsX0AhiZ49n35xTcEXsBgmJfaWNwd10=,tag:HLLP2S6nqexwq8M/VGpA2A==,type:int]
            UNLIMITED: ""
            LIMIT_PER_SEC: ENC[AES256_GCM,data:wg==,iv:8YkoL/oO3iKa4fZqB4Ko2/gne2V8CLk0AlCfMmLZSyI=,tag:xqOErPNLDFEINirAE0BWWw==,type:int]
            LIMIT_PER_MIN: ENC[AES256_GCM,data:XQ==,iv:d7NsI6UbEUnz1iF9RMX+yfXNcNczKENqBTfGV3Trrz4=,tag:l+lPT66Kjbj/DxW3ERq5YQ==,type:int]
            LIMIT_PER_HOUR: ENC[AES256_GCM,data:Nbog,iv:isA+tdPIu2D27JAt9on6BAUV91VuY+wnMueJ+6COsSM=,tag:kSmkovXTeIK5sL0BuIyuvA==,type:int]
            SMTP_SERVER_HOST: ENC[AES256_GCM,data:nSkdOJKFQp71uL65EpA=,iv:jnfc/95jvwyon2FDGV/6wJBIyqPzKXcFqjIxNXtg41w=,tag:P8No4pZUXb9e2d11fJjN+g==,type:str]
            SMTP_SERVER_PORT: ENC[AES256_GCM,data:3Wke,iv:xgFSjPJsVLeD95/P8Sc+7Z1VZu2FS0jHralx6+JvBzI=,tag:/KWEeMkkJfvsHHzJz/mVyw==,type:int]
            EMAIL_ACCOUNT: ENC[AES256_GCM,data:oYvc5pEHReZDRSZ/t/zEc0PT+fjX,iv:8cORQOh4UF6GbLRusg9IBRGIMw3dJSfTKnYcuDYf48I=,tag:WL3QXmKFHSHD/zyYxTVcyw==,type:str]
            EMAIL_PASSWORD: ENC[AES256_GCM,data:O+1Y5bPzasKjkqTWsEcI9RTp1A==,iv:f+79D3x0kA6X+cbIcRQ8Z7WH6AFXkE8fjGyJ22aDHMI=,tag:XrHYDNdZGWJ7HlaoMxfZBw==,type:str]
        command:
            - ENC[AES256_GCM,data:QyM=,iv:+59EJE6itih36R4E8p9IYpL2SxlS7bdAfODLTm6nw50=,tag:cHP2ESfd0RHZwty60GdCiQ==,type:str]
            - ENC[AES256_GCM,data:GkW3,iv:ZaUBd+SCxFZgAQJjE2uHSr+d4eiGd8jr9/NaLwzHeFw=,tag:ZfFTVShxNLCDZ+fDeZCpvw==,type:str]
            - ENC[AES256_GCM,data:cjaanirw,iv:ODza2IHpHykQI3sxcFS1B/ZXdhxcIrZB/BFpTiGRRS4=,tag:HXfwUKGDwa0sHJJy5tk9ag==,type:str]
            - ENC[AES256_GCM,data:iMg=,iv:j2L3Wyi/V5uDd3iqsDrgpqNhlQQffMu9JU2CUtQsPKs=,tag:ItvwcvEJZO9xwji9PB1ZpA==,type:str]
            - ENC[AES256_GCM,data:lX4AKph6C+IbhWW2wG5EdsHe,iv:upfzORs4MnbseD+gMoLcKwViPR6VzOqiSjsQ5ECRNlY=,tag:HIRXB/pkfM93Ua4V2B/wRg==,type:str]
            - ENC[AES256_GCM,data:T8ZB8hUE,iv:NYmVeZlTr/fhae8SIFx7cXFG/A9KIX+mEwIWZ9PB/bM=,tag:Q2dFm/W9n0hct+TdgNU2dg==,type:str]
            - ENC[AES256_GCM,data:Pn649hnDdrNhQxVCG23p,iv:rKZTd/mz76eKMdgjRl62zCbMZwMBpKrpGeIm6bXfnIc=,tag:+aewK5zvJIgU7Zsnp2pehw==,type:str]
        depends_on:
            - ENC[AES256_GCM,data:+MC5uww=,iv:Qvhk3pwRYzu9CW3jQJ8ESqK9xQGQ7LIbqF4zbUBjxJI=,tag:UcqRYSV12Y6/ER4ecpOZmA==,type:str]
        networks:
            - ENC[AES256_GCM,data:hvmo,iv:yVP4tQYtdcXdQi9xQjIMPl2mQ8I2p5hzzdw+ylGaGo8=,tag:HerEO0SkqS90qP41pO7Uew==,type:str]
    celery-scheduler:
        build:
            context: ENC[AES256_GCM,data:LQFu8gKWpZrZiQ==,iv:mqO+ftgPyKn5jwR1ymGJdEFh41UBtetx/s/55OPnHwM=,tag:L56C9a/5C6Ytfsp7AKHr9Q==,type:str]
            dockerfile: ENC[AES256_GCM,data:8ICmhGR717V1oO+e9/+o7aJADBBwt5D6S3EoBWM=,iv:iHjLh7oHJ9r3EjNzb0aDHfpa9XOk4fuMrxxDwuvU8+E=,tag:ikcrQTnv4mxGqG7hIea9wg==,type:str]
        container_name: ENC[AES256_GCM,data:rGrqkzw9OIKb,iv:XVzlV2iCFQzq8VWO3MtOafJIfmw40o8FeDRoZGEkxFM=,tag:Lr4DKwNPUWh2RRyvVUNAjw==,type:str]
        restart: ENC[AES256_GCM,data:Lyvx5XxchGVmFfrSGkE=,iv:BDCIb3UPd2dTqjv8uS1uG6BrNwpSczf0cl1bld9Rbkw=,tag:xiyVkO2N/wq8H3/mMCGMIQ==,type:str]
        environment:
            PORT: ENC[AES256_GCM,data:9NS+IQ==,iv:+YvR2Aa1LS6mD2Tfya0E5vb84RajsEv7z+fdh6vzNBY=,tag:Ds9rwR52GPC2fLMsOU0PJA==,type:int]
            REDIS_PORT: ENC[AES256_GCM,data:vgfEWA==,iv:3oLIWoJDPEwb5v1Ti2tKWR+5tTTpMZi+Jd7lk5m9LYo=,tag:dqnUVCYS5VK7/yqWhckilQ==,type:int]
            REDIS_HOST: ENC[AES256_GCM,data:SvtSRg8=,iv:uC6waCFn2m/ZSIiDPG9OzaBOk+gqSM9sC06SQ1Q3J7Q=,tag:GOIpty71xKFBhA+rzy6obQ==,type:str]
            FIREBASE_AUTH_PROJECT_ID: ENC[AES256_GCM,data:rfEuEPeM,iv:cnVwXEvqd7aAG36bcEkZMJbyoyFy2cXa6ihJc+nis08=,tag:PKixRRK1oPJaFff2zNT73Q==,type:str]
            PROXY_URL: ENC[AES256_GCM,data:FPGYhi5XTuZ7RFkgXPo=,iv:snkvHn3GRkgHoVjZ7rwkiXfUlcX5nLwoYcGu/gCMi0U=,tag:XlDRlXfoATO6h0GS8W8TtQ==,type:str]
            ADMIN_DISCORD_WEBHOOK: ENC[AES256_GCM,data:Gsku0abO0ZYr20j+5gOgCFNPmp4PB72b4UTVMcMj9jfANXmdx5ZO9UNUxPF4p/LuU9Jwc7uV0kh8I+fczQb1VMN+C7S2B1jilvgHAaCKBD+SVdfzF2xdvmpCJesnuSq2oEky7I1VNCYXBCryK08nyBFaAq0Wb2Qg2g==,iv:e0Smw7+atJkSnWDru8Ln5BBgOm96si4UEptksmt4Tjg=,tag:vFq/8PBN1HeUzELogcWb9Q==,type:str]
            DB_USERNAME: ENC[AES256_GCM,data:8rl2THsZ/VHjUfid,iv:xFslScFghuFyiOY3u451kWhrEiG9mLFFPznVlPshNwU=,tag:UpBcy4Y0gJ8mZRoyAoo/1Q==,type:str]
            DB_PASSWORD: ENC[AES256_GCM,data:I3g1jtFWrVsDSYEHcCuOwwy6,iv:X93yJbueZqdfp+b27Krn+ba0Ha1CJOuDGsXkRpKqKEA=,tag:0Tku/p4u4s4mIsDs7M/Mvw==,type:str]
            DB_AUTH_SOURCE: ENC[AES256_GCM,data:Yml9VXo=,iv:8wEFKo38iWO2LBUTYZrucj0biOGAGXCm72jVlptcpic=,tag:oJeaS2MQpteS+Lko/sebbA==,type:str]
            DB_NAME: ENC[AES256_GCM,data:IQuJf4UD,iv:n/sDphLNZt7Mkpgi1Vwu0oFQQO4wrAXVQhhrQac97dU=,tag:9fDff3g8L9GFZuKYQk0Kxg==,type:str]
            DB_HOST: ENC[AES256_GCM,data:VEA=,iv:OFah5M3RR6J2ixqYYxXX9rkpWEzf/LTz0/4qKl7pX3A=,tag:nGm5Y+34cwjjGVJOfsWmtw==,type:str]
            DB_PORT: ENC[AES256_GCM,data:k+o3Iuk=,iv:UwHQrVtaTvRjdSnvjRqs35yhk89z9yb7nbS6wk2Wf1s=,tag:+yKaN9eJqT+OulEgbk9aIg==,type:int]
            DB_REPLICASET: ENC[AES256_GCM,data:PRiX,iv:lp9oN6y03WuTG/rqUT+t+45RSkni+2WTtJmmtjTfy3E=,tag:v2lyVsnpPI2zqK9VjFf2+g==,type:str]
            INTERVAL_HOUR: ENC[AES256_GCM,data:vBw6,iv:3Smfa/DEsf+NrWnJzBXOqJdnU2/gWU5lYeyqIY/DMBg=,tag:LxR4ox7IQcTGxH2FblIBqw==,type:str]
            INTERVAL_MIN: ENC[AES256_GCM,data:Rg==,iv:aOb26upB9+yAIEeU1lRk8lAxoIo7u5fd1KP9um4Jm10=,tag:twa/gn102OnlcEH6Wbq7BQ==,type:int]
            UNLIMITED: ""
            LIMIT_PER_SEC: ENC[AES256_GCM,data:HA==,iv:iyX6LyT7Po4DZEyNDgsB28EGeKQBGGw1i53icFeOVgg=,tag:l8iwMPznhBYmGplKrymQXA==,type:int]
            LIMIT_PER_MIN: ENC[AES256_GCM,data:9g==,iv:EsTgBo+Rjvn/W4OKmzyQp4j5L8N3YMHgDvaF/axtK2M=,tag:/pW4RbR49THys9Z2qaMOaQ==,type:int]
            LIMIT_PER_HOUR: ENC[AES256_GCM,data:pRM2,iv:03y/TUVFPQjzkpu7STFH58J79Kifpk1RqIkdK/2TY+I=,tag:FXDK98ptmqLbh8i45YkL8g==,type:int]
            SMTP_SERVER_HOST: ENC[AES256_GCM,data:eOeqqZ2jCKzttI/6C9U=,iv:PbeLYGv4+7hzdtA8q0yKGB0OekZNDq0W3/+jaBkRZfg=,tag:tlQ+98QwG0QzQj0lAUb+FA==,type:str]
            SMTP_SERVER_PORT: ENC[AES256_GCM,data:AFsG,iv:qHjER2ebccZkw63PSiUOjoX2doqER4Lr+uGHI9D3XCg=,tag:9P8R6JeFNbukvW1IJgmKcg==,type:int]
            EMAIL_ACCOUNT: ENC[AES256_GCM,data:0VxHz23iwT7vVrxqt28CZdW540Z+,iv:wxPjG/QxD16TykGj0bYdaEEZyy7kATCEqULLFmAvJg0=,tag:dLpOg63F4SfpZVSrxTnQkw==,type:str]
            EMAIL_PASSWORD: ENC[AES256_GCM,data:fgwttkBy+gsgcoXSocNqU+Va8w==,iv:IfGPNhNLMI+B1l9zVqkhB1Jj4qUYXQAOpUoglD62xbs=,tag:53pIASCZ3QOgXxRhYECSBw==,type:str]
        command:
            - ENC[AES256_GCM,data:l9I=,iv:txjbhiXrr5/IUmseefk8qCDYQzWCgfzjZPGCvLKuHi4=,tag:bWuk+GboOoLpnUotDOV+jA==,type:str]
            - ENC[AES256_GCM,data:Bh9v,iv:RSMcfnMqqd3l9o6mOJKFdEcCw9iE74sOFiZhS8vyy8I=,tag:XZjdUV7JqbqsxnTqDdnu1A==,type:str]
            - ENC[AES256_GCM,data:ZVF98LMK,iv:RInqT2s++lQukr3Hh8/bj5tIANdF8AUZ7XC0b3NL7y8=,tag:ZyBlY7hP2r2Mpp0RGQMMpA==,type:str]
            - ENC[AES256_GCM,data:YqQ=,iv:JJ0HUJr8B41fUwB+Q1+KR9UkwtCz70BGlsM7sPDBASo=,tag:TdIs/JQykDjKN/QrGgQTcw==,type:str]
            - ENC[AES256_GCM,data:+TMFGhgBwrZfbjOinlIK34IU,iv:boYxJA49v7azzf53DUQjFGusaExneqAnl+zzygU0rJk=,tag:CKZW9BH/v1XA1uNyI+yzEg==,type:str]
            - ENC[AES256_GCM,data:xO5Wzg==,iv:M94xkBhTRuXSUHdvQDn8TCVctJeKdJfdk/rZtwLwvQA=,tag:yfSk3qD/miDS3yIomExEWg==,type:str]
            - ENC[AES256_GCM,data:Ysd4ImSRts8zfviqTNJh,iv:LWPdH6A4HiknnlWDEy8AEClZyUCdD8/vpf4kNrVrUyU=,tag:1QDHtzNBUJ574XRA8xDlsw==,type:str]
        depends_on:
            - ENC[AES256_GCM,data:V5si5Cr/EGIibFVKsg==,iv:KWTRE0BANlGWY0Hy0GJNsVIN1RjuNwrrvZHKdMqrl64=,tag:oVLtxblN9Y0ph1QtUocPVQ==,type:str]
        networks:
            - ENC[AES256_GCM,data:u5D7,iv:GK2Y6t9DIa5oyP5L4OXQXneA9YrIFlI4YkeXPn7Sfa8=,tag:Tl7OjXK/XcN6mSHxlTLvww==,type:str]
    tor-proxy:
        image: ENC[AES256_GCM,data:dLRL7qOJOCqsGsF2xTyugLJTp4UvZpjUJ5NegSGwy/hDnbk9LaNqAL0VjxnD8fyatZtBwmWdU2MzIpUNzuKb5xdbxDlbrMtKPSL7pAyPOZ5ZSyID1XG3bmEFuIbBORi6cvijFfeLDw==,iv:XI+TP9m6WgWfFky56g9wN4tLernQRFdg+4yAnmzbA0A=,tag:0kxzHeMnvlYhpMhIUbJNKw==,type:str]
        container_name: ENC[AES256_GCM,data:8sXZ4xJPwOnf,iv:x0sL/6SMsB2wK/0ssnapuG4V1znkCE5iIS+YdfnIu+0=,tag:NH8zyEkK900cOmXMrXLZOw==,type:str]
        restart: ENC[AES256_GCM,data:Ei8zV0tLgm6aZbRHLy8=,iv:HJgiaT7VSIsc7FDgRs+xkc15ZDQKDhJgNkzc0iV/xpI=,tag:a09Gnh/fFppqG4+E17w2fg==,type:str]
        networks:
            - ENC[AES256_GCM,data:7Ueb,iv:WbjDXwyReO8ZbebOnaxLZfdF8J1/K7PdDVq2sAZFYzg=,tag:SfQXLr5YBV86Z9sfgAeL0A==,type:str]
    api:
        build:
            context: ENC[AES256_GCM,data:nkvcn3BKdLymBA==,iv:D44Tx4FmBioDeHOIhP5lA7yJqtBLQ82qzad4cRA6sY4=,tag:7C/U1sQLDn6wPn4L1dVFbA==,type:str]
            dockerfile: ENC[AES256_GCM,data:ZOIS8EAi5+UXGDKkttxMpA4XjD+vh+brynB4o14=,iv:BmrWiHTwyrVID4DQZFN9CRAEyuou/SX5B9bNxffacPY=,tag:XN3QRMHGK6tm8VMGbELL2A==,type:str]
        container_name: ENC[AES256_GCM,data:bNIf,iv:o7qqeWQkKjKLdj/o+AGuvIgE7wy9FVsec1KXfDqzW9k=,tag:kIdCsplGRuv0Q0jJrI6PGg==,type:str]
        restart: ENC[AES256_GCM,data:cEyjTC9hQx9A5lAySF4=,iv:AcpoeV+rTVdGT7OyYyj6vnXDwrgUd6Lf0FwNV+/yQ94=,tag:+pGy2oD1YvfH2SiyabJfAQ==,type:str]
        environment:
            PORT: ENC[AES256_GCM,data:rtQd0A==,iv:VwludnYXF0f/YHAGeeEIK5SuEwc8S1/ZqGT20a9QFIA=,tag:ag6FENxz/tjNxlbojv3x0w==,type:int]
            REDIS_PORT: ENC[AES256_GCM,data:cu34hw==,iv:Jf4G/QkGT8QQ6NAilpSc0acZBYAHHzuQ17JabWuYvGQ=,tag:pjsUT2wHLOjn2Hge/pSAVw==,type:int]
            REDIS_HOST: ENC[AES256_GCM,data:Hxi7Ero=,iv:lMf81pAMk2YinFkyrAkG3/xPRotXsPnqjReKcv4yPXY=,tag:ZHamC0QEdKbj7dUEfS3Wiw==,type:str]
            FIREBASE_AUTH_PROJECT_ID: ENC[AES256_GCM,data:DvhDAu/R,iv:uazGb9ggh3HUWlprcWTJqLFELHUuWteQO6nxszr3CCs=,tag:v9VgTmJBQmDUhOsCEyaPgw==,type:str]
            PROXY_URL: ENC[AES256_GCM,data:KVQSaVxwSFG6CHyj6v8=,iv:zh/jj+2s6nXGdzvHhNH0xz6KIXrt3S4IO+hQ8NxkCPo=,tag:Tia7/44XOtbPpHrgqZOI1A==,type:str]
            ADMIN_DISCORD_WEBHOOK: ENC[AES256_GCM,data:LRPbBgqf7vKp59DL3oZxWxQSvPkIFaHoHffyNWN7Q8HM2Vhmq1WDQJHOjCRg2oJDiRbjaVLPJGhHWCCKTqO25AJpwG/A4ttB5/3b8Z1A7RhSbFRNp3Mj2DaWstnerJ1/GhmAgr/9NvjC8XKedTnFNzfwt6ZQt4Xtwg==,iv:zlSFwE90njRYU+UctUakZGqEQLZ5iNf1f7FEmod7ReU=,tag:15JIELOUW8yFDzPZBaShqA==,type:str]
            DB_USERNAME: ENC[AES256_GCM,data:o1u9ordZvddiekws,iv:PDXg0DAZE+nk5K1vlXfsn18JezybkD3sORroWAyAAow=,tag:ElqZKb0qL2J6k5GQSFHEtg==,type:str]
            DB_PASSWORD: ENC[AES256_GCM,data:MmrFBCGSrjDYH0GeMxiRLOWq,iv:6JGQrVp53GmpYfb4lPY/ims9uJyk0jE7LB4ig33TTBE=,tag:hMEBs5DUrSdbRgdSe633sw==,type:str]
            DB_AUTH_SOURCE: ENC[AES256_GCM,data:dMRvrf0=,iv:MEWmrbQ63OjWBMzQ8sr/7nZ1aqXRmXVNG98xnD1JbHs=,tag:3ZT1GcfRzm2KbD3YQSva7Q==,type:str]
            DB_NAME: ENC[AES256_GCM,data:HDnalTdD,iv:C7R4f8K7sQEv93v5GM/suPziIU7ZJBQ1cfLJ4Orn2L8=,tag:BdJOTeL06IKkfpsFBll3KQ==,type:str]
            DB_HOST: ENC[AES256_GCM,data:5KQ=,iv:z2LrKJzQph+mbwxnurEgV+TSCMEEB/C7G3H1lHwsJDw=,tag:YygMyjcUPMc8cE4xThEM/g==,type:str]
            DB_PORT: ENC[AES256_GCM,data:mJgVxEg=,iv:90tqiuiHrf6XLPWuCoq1THBgHSCuqnmqgf497aHLynM=,tag:DMZbZNQTpfjbYySwZKIzOA==,type:int]
            DB_REPLICASET: ENC[AES256_GCM,data:GHnM,iv:AoOEOXUbBxq7EG70kqI8v+2REv1XLKPfzaIGIVkzL7o=,tag:EaPiGld8AC0fYBE6zo6uPw==,type:str]
            INTERVAL_HOUR: ENC[AES256_GCM,data:eoiN,iv:IeQsrPT+b5xd+iW2T2MM7WY94gJrSdhRgxpn59yHIe4=,tag:f6cQ3BNHzHPZgLZ7h63Xjw==,type:str]
            INTERVAL_MIN: ENC[AES256_GCM,data:Eg==,iv:WZNKE24LAhFk3TUc7lIdwZd/yMJuDmUk40rdCrsyS2g=,tag:RRB8XtHiK+U2CEVcvuup2w==,type:int]
            UNLIMITED: ""
            LIMIT_PER_SEC: ENC[AES256_GCM,data:Nw==,iv:ZLRNa5n+T4VP105yym+8yFxiD6Uln48SGS+vId8tC0o=,tag:lv3RmFXInu0FRYpC1S9kiw==,type:int]
            LIMIT_PER_MIN: ENC[AES256_GCM,data:Iw==,iv:7MTwtyzVvpSd635p0OLnbgj5UHcrHONso+yjxaaZEQ8=,tag:DDiTWaU5RzaH3CbtuXpg7A==,type:int]
            LIMIT_PER_HOUR: ENC[AES256_GCM,data:b54s,iv:HIV6HvGAUkjRLo8W4Yd9W+TAuHakoNTzSJnQjOy53E4=,tag:l+eCR34MiEW/H4CYS0SMDA==,type:int]
            SMTP_SERVER_HOST: ENC[AES256_GCM,data:mkt/uFeboLiK3H2XMsY=,iv:gS3J2NpImJzBGvIN/26yjzWASeFF0kbsKh7nlOBQBZc=,tag:I687N3vHbJWNRZ8wO6l+eA==,type:str]
            SMTP_SERVER_PORT: ENC[AES256_GCM,data:UyCj,iv:dUZ7E+yrLYETxdeXI3+C9d2qjYBJEWQeHFrAanfArlc=,tag:1N15LDz7lAXrOCKTQCW0ig==,type:int]
            EMAIL_ACCOUNT: ENC[AES256_GCM,data:tSuc3fOZVfO15Fp6tL1Z9Ok+NLqc,iv:Q2BA4CgjrJ4YEyKYgdkI6NprAmmYyGFoadKKdAhrjqA=,tag:vD2lqWgXLI8cG7T2j/OAOA==,type:str]
            EMAIL_PASSWORD: ENC[AES256_GCM,data:Hi5fZGSWnCotHDzU9j5ndea0yA==,iv:yqCsc4BmZmdSzyuikn0pnIAtYsaIAx1pOIKNJqlLURA=,tag:LciGv9ozwwlA13zIqvu2hA==,type:str]
        command:
            - ENC[AES256_GCM,data:WeQ=,iv:Wd2XntakD36D/wyIHvp4Qp8Keq7Zg+CnaQc1jVFsVo0=,tag:xld95PYYigLwdNGfGv/2Pg==,type:str]
            - ENC[AES256_GCM,data:C/+3,iv:Qzm9y0t2j0JM5l99VdrE/8/LQDozNMEokQAvUsFEmy8=,tag:jhcFyQ8OyVRq66LfG0db2g==,type:str]
            - ENC[AES256_GCM,data:D++URUI3hQ==,iv:PvIBrCZ/hD/0c8c19vXOkjGS1UVzQBrKDWywYvk64Ns=,tag:R+QPyPrQE69zQUzqvTKvLA==,type:str]
            - ENC[AES256_GCM,data:eL/+,iv:OQoXnHV30bHukMsi7sI6kTB7l+JxDbSJiNAHPS2Dwoc=,tag:9D/I4X7XnxcRdCT6w9bOAA==,type:str]
            - ENC[AES256_GCM,data:bviCm2Mpl2hMemdh0Q==,iv:OpdGfRg66I/fst85R/0kSQf3rNfxIjU7H7ffPfJGPVI=,tag:4cHlxHmU6bTnxuuq/HuYDQ==,type:str]
        depends_on:
            - ENC[AES256_GCM,data:lCRr2JduHuK2cJsVng==,iv:L3hc8iCHKrrUdx7xfHLS45b1K/+NErRglcqUiWhesG4=,tag:nrXVBubYibZsWrw0vVPKGQ==,type:str]
            - ENC[AES256_GCM,data:1U0=,iv:ZowOLwkTWhkYS1VslJ7KcsAJ4AokeLk25cUTdKLfK/Y=,tag:eGFRHi7A0xeklTQv/LJFdA==,type:str]
        networks:
            - ENC[AES256_GCM,data:P9WB,iv:QCDNbX/3cEF+ZwM0r9uJB6bhix9y3GPprhIuXr1yvZ8=,tag:EjBM0DKjKcdiZWzd3A7j8w==,type:str]
            - ENC[AES256_GCM,data:EY6s,iv:ifYMyJnuhLt+8KxTYLFvCKZ1uIYEQS87MVXcGfamjPk=,tag:gfrsurMlr+sVduCiwc09Lg==,type:str]
    web:
        build:
            context: ENC[AES256_GCM,data:gMwQCbHq,iv:LFK7UbIWvoHYT9doY48HARnBRcpBiyWb6fs49IMov3c=,tag:Grxet6xO9PnslofaM3xQ7w==,type:str]
            dockerfile: ENC[AES256_GCM,data:wu/ni4yjdeTbDUk3C0+6VupP9iaNKH1bcw==,iv:Tvh1pQ1vYbiC3QzoV7EBZO7RA764SoUS/Sq2U3qwLws=,tag:CYtK829Bn3xklEghCiHFTQ==,type:str]
            args:
                VITE_PORT: ENC[AES256_GCM,data:e0Idfg==,iv:vhcJJtVvkIFKWt0KQHRiNlsGCiFcB006wihmcw29TI0=,tag:9kV/cpjVpLx0qj6m+8+yBA==,type:int]
                VITE_API_PORT: ENC[AES256_GCM,data:wrgkAg==,iv:0DtRGPztmT5myuJz2K70sz9YzEzPI4M+yWAazievb/M=,tag:4w0AwRNVAKBUW8xvKS76mQ==,type:int]
                VITE_ALLOWED_HOST: ENC[AES256_GCM,data:UUT7Soj0Kr3pUShfZNJV6Vkw,iv:VzogHWGdhekgAqmgaObKTfVitygXgDTAmVzihQr51AM=,tag:CwRNBXmiALTwBfDNPSZKqQ==,type:str]
                VITE_HOST: ENC[AES256_GCM,data:UIrPEORS+w==,iv:ITrpUIL6eGmmUG1mzP47ewkqi0QC3gqDlKFiwshagfY=,tag:fmNuibXHhGS6ppFa6yvtcg==,type:str]
                VITE_API_HOST: ENC[AES256_GCM,data:Bic1,iv:XgCabeUQ5yH3fR/qyt1kF6thHba1UWJTLEDnUzL96bs=,tag:+19jEPV0MkYftbTaMBjTqg==,type:str]
        container_name: ENC[AES256_GCM,data:Ih75jDqxeQ==,iv:eQvH+9PKjLoMPorMIyKAGZjLlZnhugrbTOce6X/NXgQ=,tag:6+svtYopIzedu7cNsQP5hQ==,type:str]
        restart: ENC[AES256_GCM,data:lb6cqrCGKi6sVO0RJ3E=,iv:RwdCY/JM3Pe+x2tnX0FIGdq50vHJayZcSbFLn31gbVc=,tag:bmltC0czIGCUTi+3BWM6QA==,type:str]
        environment:
            VITE_FIREBASE_API_KEY: ENC[AES256_GCM,data:3YxcxhIr9wyZkpvaM6OXxteNxECn38VPQDEZ+7511hhVDnFmG78E,iv:s3uRLPGDC2LXPTGpsxALp28RZalc+UZESwb72LdbfEI=,tag:85xXmplbrob5/lXhB419KQ==,type:str]
            VITE_FIREBASE_AUTH_DOMAIN: ENC[AES256_GCM,data:UK+6AwzP4uJsx5xdrWKW/h2+tEnXgQ==,iv:rV0RA0/Y04kTcqOwqVDZVEgTHKLX9MurEcaNA2PpBbw=,tag:DPt9aP8/0Nt8sRRNjh/Tmg==,type:str]
            VITE_FIREBASE_PROJECT_ID: ENC[AES256_GCM,data:eYEKSNtz,iv:7wvnI3GEKCYQB8X4qIFyZzK785QxvAFT0QaWh9ghavA=,tag:+qKJUbgzPFCsND1/rmGkqA==,type:str]
            VITE_FIREBASE_STORAGE_BUCKET: ENC[AES256_GCM,data:3H+JBfy+4gQv91V+kpQiOgw6j5/qnwhL2wM=,iv:Y6S4nU6tcn2pKhTQB+dmNNVmlQsv+PBaqFDlptixoPQ=,tag:I+Tt0mxlVKwGE3NzszZ/eQ==,type:str]
            VITE_FIREBASE_MESSAGING_SENDER_ID: ENC[AES256_GCM,data:v8PEhocPc4HeWDBP,iv:C+e6KRZQ7ej+ATsQLQcioLfJIxRyH4IgZuZSKlcoNds=,tag:3zsE4xVFh2r6Bjr/Ck81FQ==,type:int]
            VITE_FIREBASE_APP_ID: ENC[AES256_GCM,data:rhregqA1XJDZmhyDgIe87HVpVdfyYWFpTPWYnZKdfs0XnQJStyXVPuc=,iv:7O4YfNRIpVVX+Z0vcDmgangnlvL4syY4MuGVORrSORI=,tag:RSxVC5q1J7ytRAzgA7oYeg==,type:str]
            VITE_FIREBASE_MEASUREMENT_ID: ENC[AES256_GCM,data:GIlWHUZ9wH7NmhJP,iv:wDdnN8jWbJg8OI5Kk0/nb4ShY5JVJohLZm6jQoWbmRI=,tag:bfhQTdGCzKG6Ar1tMmTl4g==,type:str]
        depends_on:
            - ENC[AES256_GCM,data:k2/Q,iv:fDyXd5zzyqQFS+bVJW1ZuccidQLiGxbgQiMQJWebHt0=,tag:79xNU9HwyF2Hpekte702Xw==,type:str]
        command:
            - ENC[AES256_GCM,data:JVSk,iv:HXVfmpBsMQ/So23kuzRHL4SCyNZnoc6gziy/nHhk1lA=,tag:PdWsWhQQHe8+EyB+t6XqRQ==,type:str]
            - ENC[AES256_GCM,data:ltHE,iv:ECrisEyxCu2q9s9uaSKSpqOz1SXzLmdJdJYf4FGyvGI=,tag:X529VmOinzfU1wuyJqe6/Q==,type:str]
            - ENC[AES256_GCM,data:OjAoiSrsWA==,iv:/WZIWR4SBaqiBjzFv7uT4joQunNYVYvPuJhzeOhXK2o=,tag:RO5R31+QdwAHx4sXbgr5qw==,type:str]
        networks:
            - ENC[AES256_GCM,data:1RvM,iv:RsxE/lRTCnWcZH5v1nPLwGahvdzo/yvH3CpS9AxNoWY=,tag:31NMLY4cR8nafyoge76NDQ==,type:str]
            - ENC[AES256_GCM,data:bJjZ,iv:X/I4RFwE8ijThX+bZImr9dQYDsRAHUU8JkP4WbezPwM=,tag:jA2PxVJJ3tG5Z2erobJS6g==,type:str]
networks:
    web:
        external: ENC[AES256_GCM,data:BAb8xA==,iv:ieEq/uHmZycSPNNeX37OBMl1S6VX3HKpVFBDbTTarvs=,tag:DiHTu6gC5kWJANiz3UjPBQ==,type:bool]
    app:
        driver: ENC[AES256_GCM,data:kkpOzg0l,iv:YNnQqyoNkEeIO0TcQE5A7WUbg7UdzDoTh4+M4BYcFxc=,tag:vER2QYCVdDeD7d+hM41xvQ==,type:str]
sops:
    age:
        - recipient: age1873xyakw74p6jlcrausq0e9mmh5ch5en2l3nlg6a8d2qtxxmkqdqthddvf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN0FCOHJKSkJMdVlKMFJG
            TDdyM1RjRGpjYnpXM3ZoTVFRNVJ6Qk52U1Y4CkNmMWZpU0lnYW0rVCtZdEZKR0ZI
            VzZUWm13ZE1qc3QwQ1pDalpVZkkxL2sKLS0tIEoySG1BZkJ6STRBdW8zM0V6K0Uy
            UjlVb09YMkRFYzJDSXp5dmZEVU9KUHcK6/zikfoIUAUZ8f1nRiCIznz2aC3jOWoe
            vad2lc7vsUquIXakJ80PLjzgLI2WwZFSTSoQjRZPdDjoEmWIA2R07A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1helrvdx65wx4e7sauvut57nc288ycth5884mvxag2kmrguvgtfnqayy8uw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxR280NkRlalZqSFhiMm9P
            SGNONVkvYUo4dnJ6UWtoeGhNS1pCOGZscW0wCllsaXBRdWl5bjFSUkxxQ05Pb2hZ
            TlNEV0ZUSmVIU2hsSXppcTd0RENhTGsKLS0tIDFhQ050aEhPS2hUeVhQUXJzbGh4
            QnNtKytjRThCWDlCemNha3NGMFlFdWsKhiZm1QvinM32jqzKmtrH8XAdtEfxb5fD
            f+HIv4F7d4tLJRi5meDSKfyLXh12WPyDUKGV1FvS+vvP8FsIULAmDQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1dz94a4dhca3x3ad6jwwj63aq55sqe2fpa7d4magr2u2ggd0q4easvtm2m6
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OHdidlZ5RGVrbHZhNXNa
            Z21pdGtNMjNkZHRsWmRQb0dmOWhvYmRqd1hVCjZGNUlwODdhNEVJQWhFSHNnSHll
            MWtUaXJGK216aUJNQzlRdTFKTFlTeFUKLS0tIGxxYUxvYXQxMDhCYUIxcVZpSG42
            U3RZdDV5aUMrcmd6S3FsR3kvcW5HLzgKDqHvC7gpVpBICXi2t0oSSLvGZ3ehSMjO
            fKd2ohbB7sv67XsuV0MQv5WRe3ojmru1933zk9vyaAi1rqPJ2uYedA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ukgnhn385z298sq2wqahhfyjmtu8vfvpy2w8l3apnm3t26ztrutqwfdlg2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTUNvSUswN2tjMWpiVzk2
            Sjh6VVkyVVh6cnVNVFlneHc1UHhGS3phTVM0CkJuQktJcHNqOEhVb0d3aDR5aW4x
            SUNSOWowZlVsdVRyZ0ZBajVVOW4wS1EKLS0tIHNZcEZXQldselA2RlJDc2h3eGdP
            V1BBM3NKN1oySXZoS1hQVmhnb2RSWHcKMPDo7rLwdN0mf6oM6bTiJcOatuTfOVRI
            kxzeyxY70/6CZFV+C2hh1njOk1YAar8NQ5sYpUpVgCq1daLxPErPMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-10T09:00:12Z"
    mac: ENC[AES256_GCM,data:tPAUC0ZyJfhQWMftlKA+GWNKmNmLYAj0VhpPgbxQnuDdCR4Zic+gfbYuJuPuYIOpGPNm8BXzYheUkyS8VeCW9KIQgCDmcquGhLpab1Nt6FnqF+3E6ohI0kLDKIiadSTIg3nO+J8cko3nkROkcouZh3O50uHpxVgmmiwu7lUlsQM=,iv:Us0W1Uxd2HggRlKj7Bs9rKoI8Tb+u1nXskLpdwkGc/k=,tag:VuvsCUdcNc4NrSO39yMM7Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
